# Generated by Django 5.0.2 on 2024-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelistings', '0003_alter_product_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
